#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# options
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.50

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle 		  false
bspc config focus_follows_pointer true

bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

bspc config normal_border_color "#2a0c00"
bspc config focused_border_color "#ab1c0a"
bspc rule -a pavucontrol state=floating

# dbus
dbus-update-activation-environment --systemd --all &

# xdg
/usr/lib/xdg-desktop-portal &
/usr/lib/xdg-desktop-portal-gtk &

# us,ru layout
setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle" &

# xsetroot cursor
xsetroot -cursor_name left_ptr &

# feh
feh --bg-fill ~/wallpapers/wall.jpg &

# picom
picom -b &

# udiskie
udiskie -t &

# polybar
~/.config/polybar/launch.sh &
